import { TQuestion } from './Test'

export const questions: TQuestion[] = [
	{
		correct: 6,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/1a.png',
			'https://iqtest-pro.com/assets/img/png/1b.png',
			'https://iqtest-pro.com/assets/img/png/1c.png',
			'https://iqtest-pro.com/assets/img/png/1d.png',
			'https://iqtest-pro.com/assets/img/png/1e.png',
			'https://iqtest-pro.com/assets/img/png/1f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/1.png',
	},
	{
		correct: 1,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/2a.png',
			'https://iqtest-pro.com/assets/img/png/2b.png',
			'https://iqtest-pro.com/assets/img/png/2c.png',
			'https://iqtest-pro.com/assets/img/png/2d.png',
			'https://iqtest-pro.com/assets/img/png/2e.png',
			'https://iqtest-pro.com/assets/img/png/2f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/2.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/3a.png',
			'https://iqtest-pro.com/assets/img/png/3b.png',
			'https://iqtest-pro.com/assets/img/png/3c.png',
			'https://iqtest-pro.com/assets/img/png/3d.png',
			'https://iqtest-pro.com/assets/img/png/3e.png',
			'https://iqtest-pro.com/assets/img/png/3f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/3.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/4a.png',
			'https://iqtest-pro.com/assets/img/png/4b.png',
			'https://iqtest-pro.com/assets/img/png/4c.png',
			'https://iqtest-pro.com/assets/img/png/4d.png',
			'https://iqtest-pro.com/assets/img/png/4e.png',
			'https://iqtest-pro.com/assets/img/png/4f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/4.png',
	},
	{
		correct: 4,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/5a.png',
			'https://iqtest-pro.com/assets/img/png/5b.png',
			'https://iqtest-pro.com/assets/img/png/5c.png',
			'https://iqtest-pro.com/assets/img/png/5d.png',
			'https://iqtest-pro.com/assets/img/png/5e.png',
			'https://iqtest-pro.com/assets/img/png/5f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/5.png',
	},
	{
		correct: 2,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/6a.png',
			'https://iqtest-pro.com/assets/img/png/6b.png',
			'https://iqtest-pro.com/assets/img/png/6c.png',
			'https://iqtest-pro.com/assets/img/png/6d.png',
			'https://iqtest-pro.com/assets/img/png/6e.png',
			'https://iqtest-pro.com/assets/img/png/6f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/6.png',
	},
	{
		correct: 5,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/7a.png',
			'https://iqtest-pro.com/assets/img/png/7b.png',
			'https://iqtest-pro.com/assets/img/png/7c.png',
			'https://iqtest-pro.com/assets/img/png/7d.png',
			'https://iqtest-pro.com/assets/img/png/7e.png',
			'https://iqtest-pro.com/assets/img/png/7f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/7.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/8a.png',
			'https://iqtest-pro.com/assets/img/png/8b.png',
			'https://iqtest-pro.com/assets/img/png/8c.png',
			'https://iqtest-pro.com/assets/img/png/8d.png',
			'https://iqtest-pro.com/assets/img/png/8e.png',
			'https://iqtest-pro.com/assets/img/png/8f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/8.png',
	},
	{
		correct: 6,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/9a.png',
			'https://iqtest-pro.com/assets/img/png/9b.png',
			'https://iqtest-pro.com/assets/img/png/9c.png',
			'https://iqtest-pro.com/assets/img/png/9d.png',
			'https://iqtest-pro.com/assets/img/png/9e.png',
			'https://iqtest-pro.com/assets/img/png/9f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/9.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/10a.png',
			'https://iqtest-pro.com/assets/img/png/10b.png',
			'https://iqtest-pro.com/assets/img/png/10c.png',
			'https://iqtest-pro.com/assets/img/png/10d.png',
			'https://iqtest-pro.com/assets/img/png/10e.png',
			'https://iqtest-pro.com/assets/img/png/10f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/10.png',
	},
	{
		correct: 4,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/11a.png',
			'https://iqtest-pro.com/assets/img/png/11b.png',
			'https://iqtest-pro.com/assets/img/png/11c.png',
			'https://iqtest-pro.com/assets/img/png/11d.png',
			'https://iqtest-pro.com/assets/img/png/11e.png',
			'https://iqtest-pro.com/assets/img/png/11f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/11.png',
	},
	{
		correct: 2,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/12a.png',
			'https://iqtest-pro.com/assets/img/png/12b.png',
			'https://iqtest-pro.com/assets/img/png/12c.png',
			'https://iqtest-pro.com/assets/img/png/12d.png',
			'https://iqtest-pro.com/assets/img/png/12e.png',
			'https://iqtest-pro.com/assets/img/png/12f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/12.png',
	},
	{
		correct: 1,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/13a.png',
			'https://iqtest-pro.com/assets/img/png/13b.png',
			'https://iqtest-pro.com/assets/img/png/13c.png',
			'https://iqtest-pro.com/assets/img/png/13d.png',
			'https://iqtest-pro.com/assets/img/png/13e.png',
			'https://iqtest-pro.com/assets/img/png/13f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/13.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/14a.png',
			'https://iqtest-pro.com/assets/img/png/14b.png',
			'https://iqtest-pro.com/assets/img/png/14c.png',
			'https://iqtest-pro.com/assets/img/png/14d.png',
			'https://iqtest-pro.com/assets/img/png/14e.png',
			'https://iqtest-pro.com/assets/img/png/14f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/14.png',
	},
	{
		correct: 6,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/15a.png',
			'https://iqtest-pro.com/assets/img/png/15b.png',
			'https://iqtest-pro.com/assets/img/png/15c.png',
			'https://iqtest-pro.com/assets/img/png/15d.png',
			'https://iqtest-pro.com/assets/img/png/15e.png',
			'https://iqtest-pro.com/assets/img/png/15f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/15.png',
	},
	{
		correct: 1,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/16a.png',
			'https://iqtest-pro.com/assets/img/png/16b.png',
			'https://iqtest-pro.com/assets/img/png/16c.png',
			'https://iqtest-pro.com/assets/img/png/16d.png',
			'https://iqtest-pro.com/assets/img/png/16e.png',
			'https://iqtest-pro.com/assets/img/png/16f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/16.png',
	},
	{
		correct: 1,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/17a.png',
			'https://iqtest-pro.com/assets/img/png/17b.png',
			'https://iqtest-pro.com/assets/img/png/17c.png',
			'https://iqtest-pro.com/assets/img/png/17d.png',
			'https://iqtest-pro.com/assets/img/png/17e.png',
			'https://iqtest-pro.com/assets/img/png/17f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/17.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/18a.png',
			'https://iqtest-pro.com/assets/img/png/18b.png',
			'https://iqtest-pro.com/assets/img/png/18c.png',
			'https://iqtest-pro.com/assets/img/png/18d.png',
			'https://iqtest-pro.com/assets/img/png/18e.png',
			'https://iqtest-pro.com/assets/img/png/18f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/18.png',
	},
	{
		correct: 5,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/19a.png',
			'https://iqtest-pro.com/assets/img/png/19b.png',
			'https://iqtest-pro.com/assets/img/png/19c.png',
			'https://iqtest-pro.com/assets/img/png/19d.png',
			'https://iqtest-pro.com/assets/img/png/19e.png',
			'https://iqtest-pro.com/assets/img/png/19f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/19.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/20a.png',
			'https://iqtest-pro.com/assets/img/png/20b.png',
			'https://iqtest-pro.com/assets/img/png/20c.png',
			'https://iqtest-pro.com/assets/img/png/20d.png',
			'https://iqtest-pro.com/assets/img/png/20e.png',
			'https://iqtest-pro.com/assets/img/png/20f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/20.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/21a.png',
			'https://iqtest-pro.com/assets/img/png/21b.png',
			'https://iqtest-pro.com/assets/img/png/21c.png',
			'https://iqtest-pro.com/assets/img/png/21d.png',
			'https://iqtest-pro.com/assets/img/png/21e.png',
			'https://iqtest-pro.com/assets/img/png/21f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/21.png',
	},
	{
		correct: 3,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/22a.png',
			'https://iqtest-pro.com/assets/img/png/22b.png',
			'https://iqtest-pro.com/assets/img/png/22c.png',
			'https://iqtest-pro.com/assets/img/png/22d.png',
			'https://iqtest-pro.com/assets/img/png/22e.png',
			'https://iqtest-pro.com/assets/img/png/22f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/22.png',
	},
	{
		correct: 2,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/23a.png',
			'https://iqtest-pro.com/assets/img/png/23b.png',
			'https://iqtest-pro.com/assets/img/png/23c.png',
			'https://iqtest-pro.com/assets/img/png/23d.png',
			'https://iqtest-pro.com/assets/img/png/23e.png',
			'https://iqtest-pro.com/assets/img/png/23f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/23.png',
	},
	{
		correct: 5,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/24a.png',
			'https://iqtest-pro.com/assets/img/png/24b.png',
			'https://iqtest-pro.com/assets/img/png/24c.png',
			'https://iqtest-pro.com/assets/img/png/24d.png',
			'https://iqtest-pro.com/assets/img/png/24e.png',
			'https://iqtest-pro.com/assets/img/png/24f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/24.png',
	},
	{
		correct: 6,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/25a.png',
			'https://iqtest-pro.com/assets/img/png/25b.png',
			'https://iqtest-pro.com/assets/img/png/25c.png',
			'https://iqtest-pro.com/assets/img/png/25d.png',
			'https://iqtest-pro.com/assets/img/png/25e.png',
			'https://iqtest-pro.com/assets/img/png/25f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/25.png',
	},
	{
		correct: 4,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/26a.png',
			'https://iqtest-pro.com/assets/img/png/26b.png',
			'https://iqtest-pro.com/assets/img/png/26c.png',
			'https://iqtest-pro.com/assets/img/png/26d.png',
			'https://iqtest-pro.com/assets/img/png/26e.png',
			'https://iqtest-pro.com/assets/img/png/26f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/26.png',
	},
	{
		correct: 6,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/27a.png',
			'https://iqtest-pro.com/assets/img/png/27b.png',
			'https://iqtest-pro.com/assets/img/png/27c.png',
			'https://iqtest-pro.com/assets/img/png/27d.png',
			'https://iqtest-pro.com/assets/img/png/27e.png',
			'https://iqtest-pro.com/assets/img/png/27f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/27.png',
	},
	{
		correct: 2,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/28a.png',
			'https://iqtest-pro.com/assets/img/png/28b.png',
			'https://iqtest-pro.com/assets/img/png/28c.png',
			'https://iqtest-pro.com/assets/img/png/28d.png',
			'https://iqtest-pro.com/assets/img/png/28e.png',
			'https://iqtest-pro.com/assets/img/png/28f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/28.png',
	},
	{
		correct: 2,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/29a.png',
			'https://iqtest-pro.com/assets/img/png/29b.png',
			'https://iqtest-pro.com/assets/img/png/29c.png',
			'https://iqtest-pro.com/assets/img/png/29d.png',
			'https://iqtest-pro.com/assets/img/png/29e.png',
			'https://iqtest-pro.com/assets/img/png/29f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/29.png',
	},
	{
		correct: 4,
		variantsImg: [
			'https://iqtest-pro.com/assets/img/png/30a.png',
			'https://iqtest-pro.com/assets/img/png/30b.png',
			'https://iqtest-pro.com/assets/img/png/30c.png',
			'https://iqtest-pro.com/assets/img/png/30d.png',
			'https://iqtest-pro.com/assets/img/png/30e.png',
			'https://iqtest-pro.com/assets/img/png/30f.png',
		],
		questionImg: 'https://iqtest-pro.com/assets/img/png/30.png',
	},
]
